<div class="pokemon-cards">
    <?php
    $pokemonInfo = $block->getPokemonSelectedData();

    foreach ($pokemonInfo as $info) {
        echo '<div class="pokemon-card">';

        echo "<h2>#{$info['id']} {$info['name']}</h2>";

        echo "<img src='{$info['image']}' alt='imagen pokemon'>";

        echo "<h3>Type(s)</h3><ul>";
        foreach ($info['types'] as $type) {
            echo "<li class='lists-name'>{$type['name']}</li>";
        }
        echo "</ul>";

        echo "<h3 class='click-title'>« Show generations »</h3>";
        echo "<ul class='listing generations-list'>";
        foreach ($info['generations'] as $generation => $versionData) {
            echo "<li><span class='generation-name'>$generation</span>";
            echo "<ul class='listing'>";
            foreach ($versionData as $versionName => $sprites) {
                echo "<li class='lists-name'>$versionName</li>";
            }
            echo "</ul></li>";
        }
        echo "</ul>";

        echo "<h3 class='click-title'>« Show regions »</h3>";
        echo "<ul class='listing regions-list'>";
        if (!empty($info['regions'])) {
            foreach ($info['regions'] as $region) {
                echo "<li><span class='lists-name'>$region</span></li>";
            }
        } else {
            echo "<li><span class='lists-name'>No</span></li>";
        }
        echo "</ul>";

        echo '</div>';
    }

    ?>
</div>

<script type="text/javascript">
    require(['jquery', 'domReady!'], function($) {
        $(function() {
            const generationsLists = document.querySelectorAll(".generations-list");
            const regionsLists = document.querySelectorAll(".regions-list");

            generationsLists.forEach((list) => {
                const title = list.previousElementSibling;
                title.classList.add("clickable-title"); 

                title.addEventListener("click", () => {
                    list.style.display = list.style.display === "none" ? "block" : "none";
                });
            });

            regionsLists.forEach((list) => {
                const title = list.previousElementSibling; 
                title.classList.add("clickable-title"); 

                title.addEventListener("click", () => {
                    list.style.display = list.style.display === "none" ? "block" : "none";
                });
            });
        });
    });
</script>