<div class="pokemon-cards">
    <?php
    $pokemonInfo = $block->storeChecked();

    if ($pokemonInfo !== null) {
        foreach ($pokemonInfo as $info) {
            echo '<div class="pokemon-card">';

            echo "<h2>#{$info['id']} {$info['name']}</h2>";

            echo "<img src='{$info['image']}' alt='imagen pokemon'>";

            echo "<h3>Type(s)</h3><ul>";
            foreach ($info['types'] as $type) {
                echo "<li class='lists-name'>{$type['name']}</li>";
            }
            echo "</ul>";

            echo "<h3 class='click-title'>« Show generations »</h3>";
            echo "<ul class='listing generations-list'>";
            foreach ($info['generations'] as $generation => $versionData) {
                echo "<li><span class='generation-name'>$generation</span>";
                echo "<ul class='listing'>";
                foreach ($versionData as $versionName => $sprites) {
                    echo "<li class='lists-name'>$versionName</li>";
                }
                echo "</ul></li>";
            }
            echo "</ul>";

            echo "<h3 class='click-title'>« Show regions »</h3>";
            echo "<ul class='listing regions-list'>";
            if (!empty($info['regions'])) {
                foreach ($info['regions'] as $region) {
                    echo "<li><span class='lists-name'>$region</span></li>";
                }
            } else {
                echo "<li><span class='lists-name'>No</span></li>";
            }
            echo "</ul>";

            echo '</div>';
        }
    } else {
        echo '<h1>' . __('Page not available. Please, verify your selection in the Store View.') . '</h1>';
    }
    ?>
</div>