<div class="car-images"></div>
<script>
    require ([ 'jquery', 'mage/gallery/gallery'], function ($, Gallery) {
        $(function () {
            $('.car-images').each(function (index, element) {
                Gallery({
                    options: {
                        "autoplay": true,
                        "loop": true,
                    },
                    data: [
                        { img: "https://autotest.com.ar/wp-content/uploads/2021/08/FORD-FOCUS-ST-EDITION-2021.jpg" },
                        { img: "https://autotest.com.ar/wp-content/uploads/2023/08/Ford-Ranger-Limited-2023-19.jpg" },
                        { img: "https://autotest.com.ar/wp-content/uploads/2022/07/Ford-Maverick-Trompa-2.jpg" },
                        { img: "https://autotest.com.ar/wp-content/uploads/2023/09/RAM-1500-Rebel-trompa.jpg" },
                        { img: "https://autotest.com.ar/wp-content/uploads/2022/12/IKA-Renault-Torino-frente.jpg" }
                    ],
                }, element);
            });
        });
    });
</script>
