<?php
$blockClass = get_class($block);
echo '<h3>' . $blockClass . '</h3>';

$categoryProducts = $block->getCollection();
if ($categoryProducts != null) {
?>

<table>
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>ImagePath</th>
        <th>Precio</th>
    </tr>
    <?php

        foreach ($categoryProducts as $product) {
            echo '<tr>
            <td>' . $product->getId() . '</td>
            <td>' . $product->getName() . '</td>
            <td>' . $product->getImage() . '</td>
            <td>' . $product->getPrice() . '</td>
        </tr>';
        }
    }
    ?>
</table>
