<!--
<h2>Productos ordenados por nombre descendentemente (Limite 10 productos)</h2>
<table>
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>ImagePath</th>
    </tr>
    <?php
    $categoryProducts = $block->getProductCollectionByNameOrderDesc();
    foreach ($categoryProducts as $product) {
        echo '<tr>
            <td>' . $product->getId() . '</td>
            <td>' . $product->getName() . '</td>
            <td>' . $product->getImage() . '</td>
        </tr>';
    }
    ?>
</table>
-->

<?php
$blockClass = get_class($block);
echo '<h3>' . $blockClass . '</h3>';
?>


